[postgres]
host = "aws-1-eu-north-1.pooler.supabase.com"
user = "postgres.fcuxhcvoeobudchybomb"
password = "4TOQpT7GGwF4dLXy"
dbname = "postgres"
port = "6543"
cookie_password = "nejake-tajne-heslo-2026"
